var sectors = {
			A: "Agriculture, forestry and fishing",
			B: "Mining and quarrying",
			C: "Manufacturing",
			D: "Electricity, gas, steam and air conditioning supply",
			E: "Water supply; sewerage; waste management and remediation activities",
			F: "Construction",
			G: "Wholesale and retail trade; repair of motor vehicles and motorcycles",
			H: "Transporting and storage",
			I: "Accomodation and food service activities",
			J: "Information and communication",
			K: "Financial and insurance activities",
			L: "Real estate activities",
			M: "Professional, scientific and technical activities",
			N: "Administrative and support service activities",
			O: "Public administration and defence; compulsory social security",
			P: "Education",
			Q: "Human health and social work activities",
			R: "Arts, entertainment and recreation",
			S: "Other services activities",
			T: "Activities of households as employers; undifferentiated goods - and services - producing activities of households for own use",
			U: "Activities of extraterritorial organisations and bodies"
		},
		colors = {
			A: '#50ff00',
			B: '#4d4d4d',
			C: '#d60016',
			D: '#ffe700',
			E: '#00a8d4',
			F: '#ff0000',
			G: '#c9ff00',
			H: '#5900e7',
			I: '#ffeda1',
			J: '#dbffdb',
			K: '#ddc3ff',
			L: '#966737',
			M: '#617e67',
			N: '#a1b6c5',
			O: '#000000',
			P: '#ff78f3',
			Q: '#0dc12b',
			R: '#ffa700',
			S: '#898989',
			T: '#60381c',
			U: '#6d1a44'
		};
